# Generated by Django 3.1.3 on 2020-11-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VideoModel",
            fields=[
                ("date", models.DateField()),
                ("title", models.CharField(max_length=70)),
                ("description", models.TextField(max_length=5000)),
                (
                    "video_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="videomodel",
            index=models.Index(
                fields=["title", "description"], name="fetch_video_title_e5a75f_idx"
            ),
        ),
    ]
