# Generated by Django 3.1.3 on 2020-11-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fetch_videos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="videomodel",
            name="thumbnail",
            field=models.URLField(default="www.google.com"),
            preserve_default=False,
        ),
    ]
